### ISSUE TITLE
Como atualizar o fork.

### ISSUE THREAD

**Issue by cyntiagoulart** [andersonrocha0/tech-talents-java-matera#1]
Bom dia, Anderson!
Garfar é bom, mas tem que manter atualizado. Então, segue a sugestão de dois tutoriais para atualizar as referências bibliográficas.

https://medium.com/@dejaneves/atualizando-seu-fork-do-github-1e2a78ee4cbf
http://www.mateuspaduaweb.com.br/atualizar-sincronizar-um-repositorio-forkado-a-partir-do-repositorio-original/

Abraços.

**Comment by andersonrocha0** [comment]
Obrigado Cyntia. Vou adicionar já.

**Comment by andersonrocha0** [comment]
@cyntiagoulart https://github.com/andersonrocha0/tech-talents-java-matera/commit/3234357be6e57653b1742dd2064ea072fdf65916
